name: Check for latest hekate version
on: 
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  get-latest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.SCOPED_PAT }}
      - name: Fetch release version
        id: git-fetch
        run: |
          curl -sL https://api.github.com/repos/CTCaer/hekate/releases/latest | \
          jq -r ".tag_name" > hekate_ver
          echo ::set-output name=ver::$($(cat hekate_ver))
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")
      - name: Commit latest release version
        if: ${{ steps.git-check.outputs.modified == 'true' && steps.git-fetch.outputs.ver != 'null' }}
        run: |
          echo "new hekate version detected: $(cat hekate_ver)"
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git commit -am "Hekate $(cat hekate_ver)"
          git push
          
